# Generated by Django 6.1.1 on 2026-10-03 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronimo_vv', models.CharField(max_length=10, verbose_name='Acrônimo do Item (VV)')),
                ('titulo_3', models.CharField(max_length=150, verbose_name='Título 3 (Nome do Item)')),
                ('criado_por', models.CharField(choices=[('Rebeca', 'Rebeca'), ('Marcello', 'Marcello'), ('Bruno', 'Bruno'), ('Fábio', 'Fábio')], max_length=50, verbose_name='Criado por')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_os', models.CharField(max_length=50, unique=True, verbose_name='Ordem de Serviço (OS)')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição da OS')),
                ('criado_por', models.CharField(choices=[('Rebeca', 'Rebeca'), ('Marcello', 'Marcello'), ('Bruno', 'Bruno'), ('Fábio', 'Fábio')], max_length=50, verbose_name='Criado por')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('RT', 'Relatório técnico'), ('DT', 'Desenho técnico'), ('CRO', 'Cronograma'), ('PRO', 'Procedimento'), ('PO.PRO', 'Procedimento da produção'), ('IT.PRO', 'Instrução de trabalho da produção'), ('LM', 'Lista de Materiais'), ('PIT', 'Plano de Inspeção e teste'), ('DB', 'DataBook'), ('MC', 'Memorial de cálculo')], max_length=20, verbose_name='Tipo de Documento (UU)')),
                ('acronimo_tt', models.CharField(default='01', max_length=10, verbose_name='Sequencial/Acrônimo (TT)')),
                ('titulo_4', models.CharField(max_length=150, verbose_name='Título 4 (Dependente do Tipo de Documento)')),
                ('criado_por', models.CharField(choices=[('Rebeca', 'Rebeca'), ('Marcello', 'Marcello'), ('Bruno', 'Bruno'), ('Fábio', 'Fábio')], max_length=50, verbose_name='Criado por')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='main.item', verbose_name='Item')),
            ],
        ),
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronimo_xxx', models.CharField(max_length=10, verbose_name='Acrônimo do Conjunto (XXX)')),
                ('titulo_1', models.CharField(max_length=150, verbose_name='Título 1 (Nome do Conjunto)')),
                ('disciplina', models.CharField(choices=[('GER', 'Geral'), ('MEC', 'Mecânica')], max_length=10, verbose_name='Disciplina')),
                ('criado_por', models.CharField(choices=[('Rebeca', 'Rebeca'), ('Marcello', 'Marcello'), ('Bruno', 'Bruno'), ('Fábio', 'Fábio')], max_length=50, verbose_name='Criado por')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conjuntos', to='main.ordemservico', verbose_name='Ordem de Serviço')),
            ],
        ),
        migrations.CreateModel(
            name='Subconjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronimo_yyyy', models.CharField(max_length=10, verbose_name='Acrônimo do Subconjunto (YYYY)')),
                ('titulo_2', models.CharField(max_length=150, verbose_name='Título 2 (Nome do Subconjunto)')),
                ('criado_por', models.CharField(choices=[('Rebeca', 'Rebeca'), ('Marcello', 'Marcello'), ('Bruno', 'Bruno'), ('Fábio', 'Fábio')], max_length=50, verbose_name='Criado por')),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subconjuntos', to='main.conjunto', verbose_name='Conjunto')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='subconjunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='main.subconjunto', verbose_name='Subconjunto'),
        ),
    ]
