# Generated by Django 6.1.1 on 2026-10-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conjunto',
            name='acronimo_xxx',
        ),
        migrations.RemoveField(
            model_name='documentoitem',
            name='acronimo_tt',
        ),
        migrations.RemoveField(
            model_name='item',
            name='acronimo_vv',
        ),
        migrations.RemoveField(
            model_name='subconjunto',
            name='acronimo_yyyy',
        ),
        migrations.AddField(
            model_name='conjunto',
            name='acronimo_vv',
            field=models.CharField(default='01', max_length=10, verbose_name='Nº do Conjunto (VV)'),
        ),
        migrations.AddField(
            model_name='item',
            name='acronimo_tt',
            field=models.CharField(default='01', max_length=10, verbose_name='Nº do Item (TT)'),
        ),
        migrations.AddField(
            model_name='subconjunto',
            name='acronimo_uu',
            field=models.CharField(default='01', max_length=10, verbose_name='Nº do Subconjunto (UU)'),
        ),
        migrations.AlterField(
            model_name='conjunto',
            name='disciplina',
            field=models.CharField(choices=[('GER', 'Geral'), ('MEC', 'Mecânica')], default='MEC', max_length=10, verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='documentoitem',
            name='tipo_documento',
            field=models.CharField(choices=[('RT', 'Relatório técnico'), ('DT', 'Desenho técnico'), ('CRO', 'Cronograma'), ('PRO', 'Procedimento'), ('PO.PRO', 'Procedimento da produção'), ('IT.PRO', 'Instrução de trabalho da produção'), ('LM', 'Lista de Materiais'), ('PIT', 'Plano de Inspeção e teste'), ('DB', 'DataBook'), ('MC', 'Memorial de cálculo')], max_length=20, verbose_name='Tipo de Documento (XXX)'),
        ),
        migrations.AlterField(
            model_name='documentoitem',
            name='titulo_4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Título 4 (Dependente do Tipo)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='titulo_3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Título 3 (Opcional)'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='numero_os',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ordem de Serviço (OS - YYYY)'),
        ),
        migrations.AlterField(
            model_name='subconjunto',
            name='titulo_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Título 2 (Opcional)'),
        ),
    ]
