# Generated by Django 6.1.1 on 2026-10-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_conjunto_acronimo_xxx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjunto',
            name='acronimo_vv',
            field=models.CharField(max_length=10, verbose_name='Nº do Conjunto (VV)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='acronimo_tt',
            field=models.CharField(max_length=10, verbose_name='Nº do Item (TT)'),
        ),
        migrations.AlterField(
            model_name='subconjunto',
            name='acronimo_uu',
            field=models.CharField(max_length=10, verbose_name='Nº do Subconjunto (UU)'),
        ),
        migrations.AlterUniqueTogether(
            name='conjunto',
            unique_together={('os', 'acronimo_vv')},
        ),
    ]
