# Generated by Django 6.1.1 on 2026-10-03 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_conjunto_acronimo_vv_alter_item_acronimo_tt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentoitem',
            name='titulo_4',
        ),
    ]
