# Generated by Django 6.1.1 on 2026-10-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_documentoitem_titulo_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='esconder_titulo_2',
            field=models.BooleanField(default=False, verbose_name='Esconder Título 2'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='esconder_titulo_3',
            field=models.BooleanField(default=False, verbose_name='Esconder Título 3'),
        ),
    ]
