# Generated by Django 6.1.1 on 2026-10-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ordemservico_esconder_titulo_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='esconder_titulo_2',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='esconder_titulo_3',
        ),
        migrations.AddField(
            model_name='documentoitem',
            name='esconder_titulo_2',
            field=models.BooleanField(default=False, verbose_name='Ocultar Título 2 (Subconjunto) neste documento'),
        ),
        migrations.AddField(
            model_name='documentoitem',
            name='esconder_titulo_3',
            field=models.BooleanField(default=False, verbose_name='Ocultar Título 3 (Item) neste documento'),
        ),
    ]
