# Generated by Django 6.1.1 on 2026-10-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_ordemservico_esconder_titulo_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoitem',
            name='caminho_adicional',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Caminho adicional'),
        ),
        migrations.AddField(
            model_name='documentoitem',
            name='caminho_editavel',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Caminho para o documento editável'),
        ),
        migrations.AddField(
            model_name='documentoitem',
            name='caminho_pdf',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Caminho para o documento PDF'),
        ),
        migrations.AddField(
            model_name='documentoitem',
            name='revisao',
            field=models.CharField(choices=[('R00', 'R00'), ('R01', 'R01'), ('R02', 'R02'), ('R03', 'R03'), ('R04', 'R04'), ('R05', 'R05'), ('R06', 'R06'), ('R07', 'R07'), ('R08', 'R08'), ('R09', 'R09'), ('R10', 'R10'), ('R11', 'R11'), ('R12', 'R12'), ('R13', 'R13'), ('R14', 'R14'), ('R15', 'R15'), ('R16', 'R16'), ('R17', 'R17'), ('R18', 'R18'), ('R19', 'R19'), ('R20', 'R20')], default='R00', max_length=5, verbose_name='Revisão Atual (XX)'),
        ),
        migrations.AddField(
            model_name='documentoitem',
            name='status',
            field=models.CharField(choices=[('Não iniciado', 'Não iniciado'), ('Em elaboração', 'Em elaboração'), ('Em revisão', 'Em revisão'), ('Aprovado', 'Aprovado'), ('Em fabricação', 'Em fabricação'), ('Cancelado', 'Cancelado')], default='Em Elaboração', max_length=30, verbose_name='Status do Documento'),
        ),
    ]
