# Generated by Django 6.1.1 on 2026-10-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_documentoitem_caminho_adicional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoitem',
            name='status',
            field=models.CharField(choices=[('Não iniciado', 'Não iniciado'), ('Em elaboração', 'Em elaboração'), ('Em revisão', 'Em revisão'), ('Aprovado', 'Aprovado'), ('Em fabricação', 'Em fabricação'), ('Cancelado', 'Cancelado')], default='Não iniciado', max_length=30, verbose_name='Status do Documento'),
        ),
    ]
