# Generated by Django 6.1.1 on 2026-10-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_documentoitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoitem',
            name='caminho_adicional',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho completo adicional'),
        ),
        migrations.AlterField(
            model_name='documentoitem',
            name='caminho_editavel',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho completo do documento editável'),
        ),
        migrations.AlterField(
            model_name='documentoitem',
            name='caminho_pdf',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho completo do documento PDF'),
        ),
        migrations.AlterField(
            model_name='documentoitem',
            name='revisao',
            field=models.CharField(choices=[('R00', 'R00'), ('R01', 'R01'), ('R02', 'R02'), ('R03', 'R03'), ('R04', 'R04'), ('R05', 'R05'), ('R06', 'R06'), ('R07', 'R07'), ('R08', 'R08')], default='R00', max_length=5, verbose_name='Revisão Atual (XX)'),
        ),
    ]
