# Generated by Django 6.1.1 on 2026-10-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_documentoitem_caminho_adicional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoitem',
            name='caminho_adicional',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho adicional'),
        ),
        migrations.AlterField(
            model_name='documentoitem',
            name='caminho_editavel',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho do editável'),
        ),
        migrations.AlterField(
            model_name='documentoitem',
            name='caminho_pdf',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho do PDF'),
        ),
        migrations.AlterField(
            model_name='documentoitem',
            name='esconder_titulo_2',
            field=models.BooleanField(default=False, verbose_name='Ocultar Título 2'),
        ),
        migrations.AlterField(
            model_name='documentoitem',
            name='esconder_titulo_3',
            field=models.BooleanField(default=False, verbose_name='Ocultar Título 3'),
        ),
    ]
