# Generated by Django 6.1.1 on 2026-10-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_documentoitem_caminho_adicional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoitem',
            name='data_emissao_final',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão Final'),
        ),
        migrations.AddField(
            model_name='documentoitem',
            name='data_emissao_inicial',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão Inicial'),
        ),
        migrations.AddField(
            model_name='documentoitem',
            name='responsavel',
            field=models.CharField(blank=True, choices=[('Rebeca', 'Rebeca'), ('Marcello', 'Marcello'), ('Bruno', 'Bruno'), ('Fábio', 'Fábio')], max_length=50, null=True, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='documentoitem',
            name='revisao',
            field=models.CharField(choices=[('R00', 'R00'), ('R01', 'R01'), ('R02', 'R02'), ('R03', 'R03'), ('R04', 'R04'), ('R05', 'R05'), ('R06', 'R06'), ('R07', 'R07'), ('R08', 'R08'), ('R09', 'R09'), ('R10', 'R10'), ('R11', 'R11'), ('R12', 'R12'), ('R13', 'R13'), ('R14', 'R14'), ('R15', 'R15'), ('R16', 'R16'), ('R17', 'R17'), ('R18', 'R18'), ('R19', 'R19'), ('R20', 'R20')], default='R00', max_length=5, verbose_name='Revisão Atual (XX)'),
        ),
    ]
