# Generated by Django 6.1.1 on 2026-10-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_documentoitem_data_emissao_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjunto',
            name='titulo_1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Título 1 (Nome do Conjunto)'),
        ),
    ]
