# Generated by Django 6.1.1 on 2026-10-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_conjunto_titulo_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjunto',
            name='criado_por',
            field=models.CharField(choices=[('Rebeca Palma', 'Rebeca Palma'), ('Marcello Neto', 'Marcello Neto'), ('Bruno Romano', 'Bruno Romano'), ('Fábio Watanabe', 'Fábio Watanabe')], max_length=50, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='documentoitem',
            name='criado_por',
            field=models.CharField(choices=[('Rebeca Palma', 'Rebeca Palma'), ('Marcello Neto', 'Marcello Neto'), ('Bruno Romano', 'Bruno Romano'), ('Fábio Watanabe', 'Fábio Watanabe')], max_length=50, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='documentoitem',
            name='responsavel',
            field=models.CharField(blank=True, choices=[('Rebeca Palma', 'Rebeca Palma'), ('Marcello Neto', 'Marcello Neto'), ('Bruno Romano', 'Bruno Romano'), ('Fábio Watanabe', 'Fábio Watanabe')], max_length=50, null=True, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='item',
            name='criado_por',
            field=models.CharField(choices=[('Rebeca Palma', 'Rebeca Palma'), ('Marcello Neto', 'Marcello Neto'), ('Bruno Romano', 'Bruno Romano'), ('Fábio Watanabe', 'Fábio Watanabe')], max_length=50, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='criado_por',
            field=models.CharField(choices=[('Rebeca Palma', 'Rebeca Palma'), ('Marcello Neto', 'Marcello Neto'), ('Bruno Romano', 'Bruno Romano'), ('Fábio Watanabe', 'Fábio Watanabe')], max_length=50, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='subconjunto',
            name='criado_por',
            field=models.CharField(choices=[('Rebeca Palma', 'Rebeca Palma'), ('Marcello Neto', 'Marcello Neto'), ('Bruno Romano', 'Bruno Romano'), ('Fábio Watanabe', 'Fábio Watanabe')], max_length=50, verbose_name='Criado por'),
        ),
    ]
