# Generated by Django 6.1.1 on 2026-10-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_conjunto_criado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjunto',
            name='criado_por',
            field=models.CharField(choices=[('Rebeca Palma', 'Rebeca Palma'), ('Marcello Neto', 'Marcello Neto'), ('Bruno Romano', 'Bruno Romano'), ('Fábio Watanabe', 'Fábio Watanabe'), ('Ricardo Ferreira', 'Ricardo Ferreira')], max_length=50, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='documentoitem',
            name='criado_por',
            field=models.CharField(choices=[('Rebeca Palma', 'Rebeca Palma'), ('Marcello Neto', 'Marcello Neto'), ('Bruno Romano', 'Bruno Romano'), ('Fábio Watanabe', 'Fábio Watanabe'), ('Ricardo Ferreira', 'Ricardo Ferreira')], max_length=50, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='documentoitem',
            name='responsavel',
            field=models.CharField(blank=True, choices=[('Rebeca Palma', 'Rebeca Palma'), ('Marcello Neto', 'Marcello Neto'), ('Bruno Romano', 'Bruno Romano'), ('Fábio Watanabe', 'Fábio Watanabe'), ('Ricardo Ferreira', 'Ricardo Ferreira')], max_length=50, null=True, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='documentoitem',
            name='revisao',
            field=models.CharField(choices=[('R00', 'R00'), ('R01', 'R01'), ('R02', 'R02'), ('R03', 'R03'), ('R04', 'R04'), ('R05', 'R05'), ('R06', 'R06'), ('R07', 'R07'), ('R08', 'R08')], default='R00', max_length=5, verbose_name='Revisão Atual (XX)'),
        ),
        migrations.AlterField(
            model_name='documentoitem',
            name='status',
            field=models.CharField(choices=[('Não iniciado', 'Não iniciado'), ('Em elaboração', 'Em elaboração'), ('Em revisão', 'Em revisão'), ('Em análise', 'Em análise'), ('Para aprovação', 'Para aprovação'), ('Aprovado', 'Aprovado'), ('Em fabricação', 'Em fabricação'), ('Cancelado', 'Cancelado')], default='Não iniciado', max_length=30, verbose_name='Status do Documento'),
        ),
        migrations.AlterField(
            model_name='item',
            name='criado_por',
            field=models.CharField(choices=[('Rebeca Palma', 'Rebeca Palma'), ('Marcello Neto', 'Marcello Neto'), ('Bruno Romano', 'Bruno Romano'), ('Fábio Watanabe', 'Fábio Watanabe'), ('Ricardo Ferreira', 'Ricardo Ferreira')], max_length=50, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='criado_por',
            field=models.CharField(choices=[('Rebeca Palma', 'Rebeca Palma'), ('Marcello Neto', 'Marcello Neto'), ('Bruno Romano', 'Bruno Romano'), ('Fábio Watanabe', 'Fábio Watanabe'), ('Ricardo Ferreira', 'Ricardo Ferreira')], max_length=50, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='subconjunto',
            name='criado_por',
            field=models.CharField(choices=[('Rebeca Palma', 'Rebeca Palma'), ('Marcello Neto', 'Marcello Neto'), ('Bruno Romano', 'Bruno Romano'), ('Fábio Watanabe', 'Fábio Watanabe'), ('Ricardo Ferreira', 'Ricardo Ferreira')], max_length=50, verbose_name='Criado por'),
        ),
    ]
